### PR TITLE
Add `default` param

### PR DESCRIPTION
**Pull request by MarnuLombard**
Thinking is that the parent can pass a selected `<option>` upon initialisation.

* c250fe0 Add support for passing a `default` param
  - The item that will be selected upon initialisation of the component 
  - Allows for parent to define the selected upon load
* 00aa85b Document `default` in the `README`
* 404efb8 Compiled JS 
  - Ran `npm run build`
* 80c28ab Documented `default` param in `CHANGELOG` 
* ec41468 Handle `falsey` values passed in as default param
  - eg, `null`, `undefined`, etc
  - Extract selecting none into a method and remove duplication

### CODE REVIEW

**Comment by MarnuLombard** [comment]
Other users have requested this, see issue #19 and issue #12

**Comment by reysantana** [comment]
Is :default prop working properly, @MarnuLombard?
I tried your commits but it does not work.

**Comment by MarnuLombard** [comment]
> Is :default prop working properly, @MarnuLombard?
> I tried your commits but it does not work.

It was working fine for me by the time I opened this PR. But in all honesty I abandoned this lib in my project due to problematic dependancy definitions and lack of support. 
I moved over to `vue-simple-suggest`.

**Comment by MarnuLombard** [comment]
Closing PR due to lack of maintainer response.

**Pull request closed without merging**
